# CMake generated Testfile for 
# Source directory: C:/Users/galab/code/HiGHS/examples
# Build directory: C:/Users/galab/code/HiGHS/build-static-nohipo/examples
# 
# This file includes the relevant testing commands required for 
# testing this directory and lists subdirectories to be tested as well.
if(CTEST_CONFIGURATION_TYPE MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test([=[cxx_examples_call_highs_from_cpp]=] "C:/Users/galab/code/HiGHS/build-static-nohipo/Debug/bin/call_highs_from_cpp.exe")
  set_tests_properties([=[cxx_examples_call_highs_from_cpp]=] PROPERTIES  _BACKTRACE_TRIPLES "C:/Users/galab/code/HiGHS/cmake/cpp-highs.cmake;188;add_test;C:/Users/galab/code/HiGHS/examples/CMakeLists.txt;8;highs_cxx_test;C:/Users/galab/code/HiGHS/examples/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test([=[cxx_examples_call_highs_from_cpp]=] "C:/Users/galab/code/HiGHS/build-static-nohipo/Release/bin/call_highs_from_cpp.exe")
  set_tests_properties([=[cxx_examples_call_highs_from_cpp]=] PROPERTIES  _BACKTRACE_TRIPLES "C:/Users/galab/code/HiGHS/cmake/cpp-highs.cmake;188;add_test;C:/Users/galab/code/HiGHS/examples/CMakeLists.txt;8;highs_cxx_test;C:/Users/galab/code/HiGHS/examples/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test([=[cxx_examples_call_highs_from_cpp]=] "C:/Users/galab/code/HiGHS/build-static-nohipo/MinSizeRel/bin/call_highs_from_cpp.exe")
  set_tests_properties([=[cxx_examples_call_highs_from_cpp]=] PROPERTIES  _BACKTRACE_TRIPLES "C:/Users/galab/code/HiGHS/cmake/cpp-highs.cmake;188;add_test;C:/Users/galab/code/HiGHS/examples/CMakeLists.txt;8;highs_cxx_test;C:/Users/galab/code/HiGHS/examples/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test([=[cxx_examples_call_highs_from_cpp]=] "C:/Users/galab/code/HiGHS/build-static-nohipo/RelWithDebInfo/bin/call_highs_from_cpp.exe")
  set_tests_properties([=[cxx_examples_call_highs_from_cpp]=] PROPERTIES  _BACKTRACE_TRIPLES "C:/Users/galab/code/HiGHS/cmake/cpp-highs.cmake;188;add_test;C:/Users/galab/code/HiGHS/examples/CMakeLists.txt;8;highs_cxx_test;C:/Users/galab/code/HiGHS/examples/CMakeLists.txt;0;")
else()
  add_test([=[cxx_examples_call_highs_from_cpp]=] NOT_AVAILABLE)
endif()
if(CTEST_CONFIGURATION_TYPE MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test([=[c_examples_call_highs_from_c_minimal]=] "C:/Users/galab/code/HiGHS/build-static-nohipo/Debug/bin/call_highs_from_c_minimal.exe")
  set_tests_properties([=[c_examples_call_highs_from_c_minimal]=] PROPERTIES  _BACKTRACE_TRIPLES "C:/Users/galab/code/HiGHS/cmake/cpp-highs.cmake;235;add_test;C:/Users/galab/code/HiGHS/examples/CMakeLists.txt;24;highs_c_test;C:/Users/galab/code/HiGHS/examples/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test([=[c_examples_call_highs_from_c_minimal]=] "C:/Users/galab/code/HiGHS/build-static-nohipo/Release/bin/call_highs_from_c_minimal.exe")
  set_tests_properties([=[c_examples_call_highs_from_c_minimal]=] PROPERTIES  _BACKTRACE_TRIPLES "C:/Users/galab/code/HiGHS/cmake/cpp-highs.cmake;235;add_test;C:/Users/galab/code/HiGHS/examples/CMakeLists.txt;24;highs_c_test;C:/Users/galab/code/HiGHS/examples/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test([=[c_examples_call_highs_from_c_minimal]=] "C:/Users/galab/code/HiGHS/build-static-nohipo/MinSizeRel/bin/call_highs_from_c_minimal.exe")
  set_tests_properties([=[c_examples_call_highs_from_c_minimal]=] PROPERTIES  _BACKTRACE_TRIPLES "C:/Users/galab/code/HiGHS/cmake/cpp-highs.cmake;235;add_test;C:/Users/galab/code/HiGHS/examples/CMakeLists.txt;24;highs_c_test;C:/Users/galab/code/HiGHS/examples/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test([=[c_examples_call_highs_from_c_minimal]=] "C:/Users/galab/code/HiGHS/build-static-nohipo/RelWithDebInfo/bin/call_highs_from_c_minimal.exe")
  set_tests_properties([=[c_examples_call_highs_from_c_minimal]=] PROPERTIES  _BACKTRACE_TRIPLES "C:/Users/galab/code/HiGHS/cmake/cpp-highs.cmake;235;add_test;C:/Users/galab/code/HiGHS/examples/CMakeLists.txt;24;highs_c_test;C:/Users/galab/code/HiGHS/examples/CMakeLists.txt;0;")
else()
  add_test([=[c_examples_call_highs_from_c_minimal]=] NOT_AVAILABLE)
endif()
