name: test-clang-format

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - uses: DoozyX/clang-format-lint-action@v0.5
      with:
        source: './src'
        exclude: './src/ipm/basiclu/src|./src/ipm/basiclu/include'
        extensions: 'h,cpp,c'
        clangFormatVersion: 9
