name: hipo-fetch

on: [push, pull_request]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

env:
  # do not use vcpkg for this workflow
  VCPKG_INSTALLATION_ROOT: ""

jobs:
  ubuntu_arm:
    runs-on: ${{ matrix.os }}

    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-24.04-arm]
        config: [Release]
        all_tests: [ON]

    steps:
      - uses: actions/checkout@v6

      - name: Create Build Environment
        run: cmake -E make_directory ${{github.workspace}}/build

      - name: Configure CMake
        working-directory: ${{github.workspace}}/build
        run: |
          cmake $GITHUB_WORKSPACE -DHIPO=ON -DBUILD_OPENBLAS=ON \
            -DALL_TESTS=${{ matrix.all_tests }}

      - name: Build
        working-directory: ${{github.workspace}}/build
        run: |
          cmake --build . -j2

      - name: Test executable
        working-directory: ${{github.workspace}}/build
        run: ./bin/highs --solver=hipo $GITHUB_WORKSPACE/check/instances/afiro.mps

      - name: Debug through SSH
        uses: edipizarro/runner-open-ssh @main
        with:
          sshPublicKey: ${{ secrets.SSH_PUBLIC_KEY }}
          gatewayPrivateKey: ${{ secrets.GATEWAY_PRIVATE_KEY }}
          gatewayIP: ${{ secrets.GATEWAY_IP }}
          gatewayUser: ${{ secrets.GATEWAY_USER }}
          maxLifeTime: 30
          port: 2222  # Optional: defaults to 2222


