name: sanitizers-cmake

on: [push, pull_request]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  hipo:
    runs-on: ${{ matrix.os }}

    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest]
        config: [RelWithDebInfo]
        all_tests: [OFF]
        sanitizer: [Thread]
        iteration: [1, 2, 3, 4, 5, 6, 7, 8, 9, 10]

    steps:
      - uses: actions/checkout@v6

      - name: Create Build Environment
        run: cmake -E make_directory ${{github.workspace}}/build

      - name: Configure CMake
        working-directory: ${{github.workspace}}/build
        run: |
          cmake $GITHUB_WORKSPACE -DHIPO=ON -DBUILD_OPENBLAS=ON \
            -DALL_TESTS=${{ matrix.all_tests }} \
            -DCMAKE_BUILD_TYPE=${{ matrix.config }} \
            -DDEBUG_MEMORY=${{ matrix.sanitizer }} \
            -DNO_AVX512=ON \
            -DCMAKE_INTERPROCEDURAL_OPTIMIZATION=OFF \
            -DCMAKE_C_COMPILER=gcc -DCMAKE_CXX_COMPILER=g++


      - name: Build
        working-directory: ${{github.workspace}}/build
        run: |
          cmake --build . -j2

      - name: Run 6-10
        if: ${{ matrix.iteration <= 5 }}
        run: |
          echo "hipo_system=normaleq" > options1.opt
          echo "hipo_ordering=metis" > options2.opt
          ./bin/highs --solver=hipo --options_file=options1.opt $GITHUB_WORKSPACE/check/instances/afiro.mps
          ./bin/highs --solver=hipo --options_file=options2.opt $GITHUB_WORKSPACE/check/instances/afiro.mps

      - name: Run 1-5
        if: ${{ matrix.iteration > 5 }}
        run: |
          echo "hipo_system=normaleq" > options1.opt
          echo "hipo_ordering=metis" > options2.opt
          ./bin/highs --solver=hipo --options_file=options2.opt $GITHUB_WORKSPACE/check/instances/afiro.mps
          ./bin/highs --solver=hipo --options_file=options1.opt $GITHUB_WORKSPACE/check/instances/afiro.mps
