name: valgrind

on: [push, pull_request]

jobs:
  unit_tests:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest]

    steps:
      - uses: actions/checkout@v4
      
      - name: Install Valgrind
        run: sudo apt-get update && sudo apt-get install valgrind

      - name: Create Build Environment
        run: cmake -E make_directory ${{runner.workspace}}/build

      - name: Configure CMake
        shell: bash
        working-directory: ${{runner.workspace}}/build
        run: cmake $GITHUB_WORKSPACE -DCMAKE_BUILD_TYPE=Debug -DALL_TESTS=ON

      - name: Build
        working-directory: ${{runner.workspace}}/build
        shell: bash
        run: |
          cmake --build . --parallel 

      - name: Test
        working-directory: ${{runner.workspace}}/build
        shell: bash
        run: |
          valgrind \
          --error-exitcode=1 \
          --leak-check=full \
          --show-leak-kinds=all \
          --track-origins=yes \
          -s \
          ./bin/unit_tests 

  instance_tests:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest]

    steps:
      - uses: actions/checkout@v4

      - name: Install Valgrind
        run: sudo apt-get update && sudo apt-get install valgrind
      
      - name: Create Build Environment
        run: cmake -E make_directory ${{runner.workspace}}/build

      - name: Configure CMake All
        shell: bash
        working-directory: ${{runner.workspace}}/build
        run: cmake $GITHUB_WORKSPACE -DCMAKE_BUILD_TYPE=Debug -DALL_TESTS=ON

      - name: Build All
        working-directory: ${{runner.workspace}}/build
        shell: bash
        run: |
          cmake --build . --parallel 

      - name: Test
        working-directory: ${{runner.workspace}}/build
        shell: bash
        run: |
          valgrind \
            --error-exitcode=1 \
            --leak-check=full \
            --show-leak-kinds=all \
            --track-origins=yes \
            -s ctest -E unit.* \
            --timeout 1000 \
            --output-on-failure \
  
